FROM oven/bun:alpine as builder

WORKDIR /app

COPY ./tsconfig.json .

COPY ./packages/frontend/ ./packages/frontend/

WORKDIR /app/packages/frontend

RUN bun install

ENV NODE_ENV="production"

RUN bun run build

FROM nginx:alpine-slim as production

WORKDIR /app

COPY --from=builder /app/packages/frontend/dist/ /usr/share/nginx/html
COPY ./.docker/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
