/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/vk': {
    get: operations['AuthController_authVk'];
  };
  '/api/auth/google': {
    get: operations['AuthController_authGoogle'];
  };
  '/api/auth/logout': {
    post: operations['AuthController_logout'];
  };
  '/api/user': {
    get: operations['UserController_getSelf'];
  };
  '/api/utils': {
    get: operations['UtilsController_getOAuthList'];
  };
  '/api/board/new': {
    post: operations['BoardController_createBoard'];
  };
  '/api/board/list': {
    get: operations['BoardController_getUserList'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UserEntity: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      lastActiveAt: string;
      username: string;
      avatar: string;
    };
    AuthMethodDTO: {
      /** @enum {string} */
      type: 'vk' | 'google';
      redirect_url: string;
    };
    AuthMethodsDTO: {
      items: components['schemas']['AuthMethodDTO'][];
    };
    CreateBoardDTO: {
      title: string;
    };
    BoardEntity: {
      /** @example fxrJQl4u */
      id: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** @example My Board */
      title: string;
      /** @example 1 */
      owner: number;
      /** @example my-board */
      slug: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  AuthController_authVk: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_authGoogle: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      201: {
        content: never;
      };
    };
  };
  UserController_getSelf: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['UserEntity'];
        };
      };
    };
  };
  UtilsController_getOAuthList: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['AuthMethodsDTO'];
        };
      };
    };
  };
  BoardController_createBoard: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateBoardDTO'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['BoardEntity'];
        };
      };
    };
  };
  BoardController_getUserList: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['BoardEntity'][];
        };
      };
    };
  };
}
