/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/vk': {
    get: operations['AuthController_authVk'];
  };
  '/api/auth/google': {
    get: operations['AuthController_authGoogle'];
  };
  '/api/auth/logout': {
    get: operations['AuthController_logout'];
  };
  '/api/user': {
    get: operations['UserController_getSelf'];
  };
  '/api/utils': {
    get: operations['UtilsController_getOAuthList'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    User: {
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: date-time */
      lastActiveAt: string;
      username: string;
      avatar: string;
    };
    OAuthMethodDTO: {
      /** @enum {string} */
      type: 'vk' | 'google';
      redirect_url: string;
    };
    OAuthMethodsDTO: {
      items: components['schemas']['OAuthMethodDTO'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  AuthController_authVk: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_authGoogle: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  AuthController_logout: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  UserController_getSelf: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  UtilsController_getOAuthList: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['OAuthMethodsDTO'];
        };
      };
    };
  };
}
